export const PRISMA_FIELDS = [
  { key: 'internalArticleNumber', label: 'Artikel Nummer (ID)', type: 'string' },
  { key: 'rel_supplier', label: 'Leverancier (Naam)', type: 'relation' },
  { key: 'rel_brand', label: 'Merk (Naam)', type: 'relation' },
  { key: 'title', label: 'Titel / Naam', type: 'string' },
  { key: 'seoTitle', label: 'SEO Titel', type: 'string' },
  { key: 'longDescription', label: 'Lange Omschrijving', type: 'string' },
  { key: 'color', label: 'Kleur', type: 'string' },
  { key: 'mainMaterial', label: 'Hoofdmateriaal', type: 'string' },
  { key: 'ingredients', label: 'Ingrediënten', type: 'string' },
  { key: 'allergens', label: 'Allergenen', type: 'string' },
  { key: 'supplierContacted', label: 'Leverancier benaderd?', type: 'string' },
  { key: 'critTransportVehicle', label: 'Vervoersmiddel', type: 'string' },
  { key: 'critOther', label: 'Overige vermelding', type: 'string' },
  { key: 'readyForImport', label: 'Klaar voor import', type: 'string' },
  { key: 'internalRemarks', label: 'Interne Communicatie', type: 'string' },
  // Numbers
  { key: 'weightGr', label: 'Gewicht (gr)', type: 'number' },
  { key: 'lengthCm', label: 'Lengte (cm)', type: 'number' },
  { key: 'widthCm', label: 'Breedte (cm)', type: 'number' },
  { key: 'heightCm', label: 'Hoogte (cm)', type: 'number' },
  { key: 'volumeMl', label: 'Inhoud (ml)', type: 'number' },
  { key: 'volumeGr', label: 'Inhoud (gr)', type: 'number' },
  { key: 'critTransportDistance', label: 'Afstand (km)', type: 'number' },
  // Bools
  { key: 'systemActive', label: 'Actief in Systeem?', type: 'boolean' },
  { key: 'webshopActive', label: 'Actief op Webshop?', type: 'boolean' },
  // Criteria
  { key: 'critMensSocial', label: 'Maatschappelijke betrokkenheid', type: 'string' },
  { key: 'critMensSafeWork', label: 'Veilige werkomgeving', type: 'string' },
  { key: 'critMensFairWage', label: 'Eerlijk loon', type: 'string' },
  { key: 'critDierCrueltyFree', label: 'Diervrij', type: 'string' },
  { key: 'critDierFriendly', label: 'Diervriendelijk', type: 'string' },
  { key: 'critMilieuPackagingFree', label: 'Verpakkingsvrij', type: 'string' },
  { key: 'critMilieuPlasticFree', label: 'Plastic vrij', type: 'string' },
  { key: 'critMilieuRecyclable', label: 'Recyclebaar', type: 'string' },
  { key: 'critMilieuBiodegradable', label: 'Afbreekbaar', type: 'string' },
  { key: 'critMilieuCompostable', label: 'Composteerbaar', type: 'string' },
  { key: 'critHandmade', label: 'Handgemaakt', type: 'string' },
  { key: 'critNatural', label: 'Natuurlijk', type: 'string' },
  { key: 'critCircular', label: 'Circulair/Hergebruik', type: 'string' },
  { key: 'critMilieuCarbonCompensated', label: 'Uitstootcompensatie', type: 'string' },
];
